<?php

##############################################################################
# Please do not edit this file. These are default application settings.
# To override any of these variables include them in config.php
##############################################################################
$debug = 0;

$memcache_server = "localhost";
$memcache_port = 11211;

$minimum_hits_for_display = 100;

# Memcache key prefixes
$URL_REQ_MC_PREFIX = "urlreq-";
$URL_TOTAL_TIME_MC_PREFIX = "totaltime-";
$URL_NINETIETH_MC_PREFIX = "ninetime-";
$ALL_STATS_MC_PREFIX = "allstats-";

# Adjust to the patterns you really care about. For example if you want
# URLs that have html, link, wap servlet and jsp in them do this
#$valid_url_patterns = "/(html|link|wap|servlet|jsp)/";
# By default any URL pattern is acceptable
# This is perhaps superflous but we'll leave it in for now
$valid_url_patterns = "/.*/";

?>
